export const data = [
  {
    id: 1,
    title: "Πίτσα",
    ingredients: ["ντομάτα", "γκούντα", "γαλοπούλα", "μανητάρια", "πιπεριά"],
    price: 10,
    currency: "€",
    imgPath: "./assets/pizza.png",
    quantity: 10,
  },
  {
    id: 2,
    title: "Μπέργκερ",
    ingredients: ["ντομάτα", "χοιρινό μπιφτέκι", "σος", "μαρούλι", "γκούντα"],
    price: 7,
    currency: "€",
    imgPath: "./assets/burger.png",
    quantity: 10,
  },
  {
    id: 3,
    title: "Σάντουιτς",
    ingredients: [
      "ντομάτα",
      "γκούντα",
      "γαλοπούλα",
      "μαρούλι",
      "κέτσαπ",
      "μαγιονέζα",
      "κρεμμύδι",
      "αυγό",
    ],
    price: 4,
    currency: "€",
    imgPath: "./assets/sandwitch.png",
    quantity: 10,
  },
  {
    id: 4,
    title: "Σαλάτα",
    ingredients: [
      "μαρούλι",
      "κρουτόν",
      "ντοματίνια",
      "ζαμπόν",
      "γκούντα",
      "μαγιονέζα",
      "καλαμπόκι",
    ],
    price: 3,
    currency: "€",
    imgPath: "./assets/salad.png",
    quantity: 10,
  },
  {
    id: 5,
    title: "Τοστ",
    ingredients: ["γκούντα", "καπνιστή μπριζόλα", "φιλαδέλφεια"],
    price: 2.5,
    currency: "€",
    imgPath: "./assets/toast.png",
    quantity: 10,
  },
  {
    id: 6,
    title: "Κόκα κόλα",
    ingredients: [],
    price: 1,
    currency: "€",
    imgPath: "./assets/coca-cola.png",
    quantity: 10,
  },
  {
    id: 7,
    title: "Πορτοκαλάδα",
    ingredients: [],
    price: 1,
    currency: "€",
    imgPath: "./assets/juice.png",
    quantity: 10,
  },
  {
    id: 8,
    title: "Νερό",
    ingredients: [],
    price: 0.5,
    currency: "€",
    imgPath: "./assets/water.png",
    quantity: 10,
  },
  {
    id: 9,
    title: "Μπουγάτσα",
    ingredients: [],
    price: 2.5,
    currency: "€",
    imgPath: "./assets/bougatsa.png",
    quantity: 10,
  },
  {
    id: 10,
    title: "Κουλούρι Θεσσαλονίκης",
    ingredients: [],
    price: 0.5,
    currency: "€",
    imgPath: "./assets/koulouri.png",
    quantity: 10,
  },
];
